name: Compile Games
on: 
  repository_dispatch:
  pull_request: 
      branches: [ master ] 


jobs:
  install-splashkit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SplashKit
        run: | 
          bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)
      # after install splashkit step check if it is installed
      - name: Add splashkit to path
        run: echo "$HOME/.splashkit" >> $GITHUB_PATH
      - name: Install dependencies, compile splashkit
        run: ls
        # run: skm linux install
      - name: "Find added games"
        run: |
          echo "$GITHUB_HEAD_REF"
          cd $GITHUB_WORKSPACE
          ls
          DIR=$(git diff origin/master...origin/${GITHUB_HEAD_REF} --dirstat --diff-filter=A games/ | sed 's/^[ 0-9.]\+% //g')
          echo $DIR

  # with:.
    # cd $GITHUB_WORKSPACE
  #   ref: my-branch
        
          # git branch --show-current

#git diff master...feature/compile-games --dirstat --diff-filter=A games/
# git diff ecb3d6d47b5ceb785e1b8cd2826a69457a7259d9 --diff-filter=A --name-only games/
# git diff master...feature/compile-games --diff-filter=A --name-only games/


