name: Compile Games
on: 
  repository_dispatch:
  pull_request: 
      branches: [ master ] 


jobs:
  install-splashkit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install SplashKit
        run: | 
          bash <(curl -s https://raw.githubusercontent.com/splashkit/skm/master/install-scripts/skm-install.sh)
      # after install splashkit step check if it is installed
      - name: Add splashkit to path
        run: echo "$HOME/.splashkit" >> $GITHUB_PATH
      - name: Install dependencies, compile splashkit
        run: skm linux install
      - name: "branch"
        run: |
          cd $GITHUB_WORKSPACE
          ls
          echo "$GITHUB_REF"
          git branch --show-current
          echo "test"
  # with:.
  #   ref: my-branch
        

# git diff ecb3d6d47b5ceb785e1b8cd2826a69457a7259d9 --diff-filter=A --name-only games/
# git diff master...feature/compile-games --diff-filter=A --name-only games/


