name: Validate Game

on:
  pull_request:
    branches: [ master ]

jobs: 
  validate-game: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate-config
        run: |
          set -e
          for game in "$GITHUB_WORKSPACE/arcade-games/"*
          echo "Validating ${game}"
          do
            ./config-test.sh ${game}/config.txt
            echo
          done