name: ValidateGame

on:
  pull_request:
    branches: [ main ]

jobs: 
  validate-game: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./config-test.sh $GITHUB_WORKSPACE/arcade-games/Game1/config.txt

