name: Validate Game

on:
  pull_request:
    branches: [ master ]

jobs: 
  validate-game: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate-config
        run: |
          ls
          set -e
          ./config-test.sh $GITHUB_WORKSPACE/arcade-games/Game2/config.txt